# Generated by Django 4.0.4 on 2022-10-11 14:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('voting', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='votinglist',
            name='category',
            field=models.CharField(default='creativity', max_length=20),
            preserve_default=False,
        ),
    ]
