# Generated by Django 4.0.4 on 2022-10-17 14:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('voting', '0002_votinglist_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='creation',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='creations'),
        ),
    ]
