# Generated by Django 4.0.4 on 2022-07-25 00:17

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('voting', '0002_delete_tutorialcategory'),
    ]

    operations = [
        migrations.CreateModel(
            name='VotingList',
            fields=[
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
                ('vote', models.IntegerField(blank=True, null=True)),
                ('creation', models.ManyToManyField(to='voting.creation')),
            ],
        ),
    ]
