# Generated by Django 4.1.1 on 2022-10-18 13:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('voting', '0005_alter_creation_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='creation',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='creations/'),
        ),
    ]
