# Generated by Django 4.1.1 on 2022-10-18 13:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('voting', '0006_alter_creation_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='creation',
            name='number',
            field=models.IntegerField(default=1, unique=True),
            preserve_default=False,
        ),
    ]
