# Generated by Django 4.0.4 on 2022-11-10 00:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('voting', '0007_creation_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='creation',
            name='creator',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='creation',
            name='description',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='creation',
            name='name',
            field=models.CharField(max_length=100),
        ),
    ]
